export enum SortBy {
  NAME = "NAME",
  RECENCY = "RECENCY",
  LOWEST_PRICE = "LOWEST_PRICE",
  HIGHEST_PRICE = "HIGHEST_PRICE",
  LOWEST_PRICE_PER_UNIT = "LOWEST_PRICE_PER_UNIT",
  HIGHEST_PRICE_PER_UNIT = "HIGHEST_PRICE_PER_UNIT",
}
