import { nextAuth } from "@/auth";
import { Header } from "@/components/header";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import { redirect } from "next/navigation";
import "./globals.css";
import { ApolloWrapper } from "@/app/ApolloWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await nextAuth.auth();
  if (!session) {
    redirect("/api/auth/signin");
  }
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <ApolloWrapper>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-svh overflow-hidden`}
          >
            <Header />
            <div className="flex-1 w-full overflow-scroll">{children}</div>
          </body>
        </ApolloWrapper>
      </SessionProvider>
    </html>
  );
}
