#!/bin/sh

# Get the list of staged files
STAGED_FILES=$(git diff --cached --name-only)

CHANGES_IN_PACKAGES=false
for FILE in $STAGED_FILES; do
  if [[ $FILE == packages/* ]]; then
    CHANGES_IN_PACKAGES=true
    break
  fi
done


if [ "$CHANGES_IN_PACKAGES" = true ]; then
  pnpm install
fi

# Run lint and cancel the commit if there are errors
pnpm run --filter "@app/*" lint
if [ $? -ne 0 ]; then
  echo "Lint errors found. Commit canceled."
  exit 1
fi

exit 0