#!/usr/bin/env sh
# Get the current branch name
branch_name=$(git symbolic-ref --short HEAD)

# Get the current commit message
commit_file=$1
commit_message=$(cat "$commit_file")

# Check if the branch name is already a prefix
if [[ $commit_message != "$branch_name "* ]]; then
  # Prepend the branch name to the commit message
  echo "$branch_name: $commit_message" > "$commit_file"
fi